import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { getHomePage, getPages } from '../lib/dato'

import ListPages from '../components/ListPages-with-image';
import Hero from '../components/Hero';


export default function Index({ preview, page, pages }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app..." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        title={page.title}
        intro={page.strapLine}
        coverImage ={page.backgroundImage.responsiveImage}
        slug='index'
      />

      {pages.length > 0 && <ListPages pages={pages} />}

    </>

  )
}

// This function gets called at build time
export async function getStaticProps({ preview = false }) {

  const data = await getHomePage(preview) || []
  const pages = await getPages(preview) || []

  return {
    props: {
      preview,
      page: {
        ...data?.home
      },
      pages
    },
  };
}
