import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { getPageAndMorePages } from '../lib/dato'

import ListPages from '../components/ListPages';
import PageHeader from '../components/PageHeader';

// This function gets called at build time
export async function getStaticProps({ preview = false }) {

  const data = await getPageAndMorePages('index', preview) || []
  // By returning { props: { page } }, the Blog component will receive `page` as a prop at build time
  return {
     props: { 
      preview,
      page: {
          ...data?.page
        },
      morePages: data?.morePages ?? [],
    },
  };
}

export default function Index({ preview, morePages, page }) {

  return (
    <>
  
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <PageHeader title={page.title} />
        
        <ListPages pages={morePages}/>
        
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      </main>
      </>

  )
}
