import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { getPageAndMorePages } from '../lib/dato'

import ListPages from '../components/ListPages-with-image';
import PageHeader from '../components/PageHeader';

// This function gets called at build time
export async function getStaticProps({ preview = false }) {

  const data = await getPageAndMorePages('index', preview) || []
  // By returning { props: { page } }, the Blog component will receive `page` as a prop at build time
  return {
    props: {
      preview,
      page: {
        ...data ?.page
        },
      morePages: data ?.morePages ?? [],
    },
  };
}

export default function Index({ preview, morePages, page }) {

  return (
    <>

      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app." />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeader
        title={page.title}
        intro={page.strapLine}
        coverImage={page.backgroundImage.responsiveImage}
      />

      <ListPages pages={morePages} />

    </>

  )
}
